import { defineConfig } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

// Auto-generated by FullQA.ai. Runs headed and slowed down so you can watch.
//
// 1) Loads qa-scripts/.env into process.env (QA_BASE_URL, QA_USERNAME,
//    QA_PASSWORD, QA_LOGIN_URL) so specs get test credentials at run time —
//    no secrets are stored inside the .spec.ts files.
// 2) storageState: if you log in once with the 'setup' project, every spec
//    starts already authenticated. Create/refresh the saved session with:
//       npx playwright test --project=setup
const envFile = path.join(__dirname, '.env');
if (fs.existsSync(envFile)) {
  for (const line of fs.readFileSync(envFile, 'utf-8').split(/\r?\n/)) {
    if (line.trim().startsWith('#')) continue;
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/);
    if (m && process.env[m[1]] === undefined) {
      process.env[m[1]] = m[2].replace(/^["']|["']$/g, '');
    }
  }
}

const authFile = path.join(__dirname, '.auth', 'state.json');
const storageState = fs.existsSync(authFile) ? authFile : undefined;

const base = {
  headless: false,
  launchOptions: { slowMo: 350 },
  viewport: { width: 1280, height: 800 },
  // A step whose element never appears must fail fast with its name —
  // not hang until the whole-test timeout.
  actionTimeout: 20_000,
  screenshot: 'only-on-failure' as const,
};

export default defineConfig({
  testDir: '.',
  fullyParallel: false,
  workers: 1,
  reporter: 'list',
  // Recorded flows replay MANY steps headed + slowMo: Playwright's default
  // 30s-per-test budget dies mid-flow (right after login on long sessions).
  timeout: 300_000,
  expect: { timeout: 10_000 },
  projects: [
    // Logs in with QA_* and saves the session. Run explicitly: --project=setup
    { name: 'setup', testMatch: /auth\.setup\.ts/, use: { ...base } },
    // Normal specs — reuse the saved login if it exists.
    { name: 'chromium', testMatch: /\.spec\.ts$/, use: { ...base, storageState } },
  ],
});
